### ISSUE TITLE
Aurelia

### ISSUE THREAD

**Issue by vfrank66** [danielpquinn/springfield-web-spa#1]
Here is a quick article on aurelia:
http://ilikekillnerds.com/2015/01/aurelia-vs-angularjs-round-one-fight/

**Comment by danielpquinn** [comment]
Nice. I would have to do some more research to figure out how Aurelia differs from Angular 2.0, but I like the author's decision to go with standards-based solutions wherever possible.

**Comment by vfrank66** [comment]
Yeah I didn't know if you had heard of it. I am fearful to work in angular with the changes coming and no having had a background in angular originally, but I might be going about it wrong
