### ISSUE TITLE
Dynamic Routing in Aurelia - Alter Title

### ISSUE THREAD

**Issue by ClareBear85** [danielpquinn/springfield-web-spa#2]
{ 
        route: 'content/:id',
        name: 'Details', 
        title: 'Details',
        viewPorts: { main: { moduleId: './admin/content/details' }, aside: { moduleId: './admin/content/aside' } }, 
        settings: { menu:menuSection.content, access: { controller: 'content', action: 'get' } }
    },
    { 
        route: 'content/:id',
        name: 'Add', 
        viewPorts: { main: { moduleId: './admin/content/details' }, aside: { moduleId: './admin/content/aside' } }, 
        settings: { menu:menuSection.content, access: { controller: 'content', action: 'get' } }
        title: 'Add',
        href: 'content/0',
        nav: true
    }   

```
import {Router} from 'aurelia-router'; 

activate(){
    if (this.id === 0) {
        this.router.title = "Add";
    } else {
        this.router.title = "Edit";
    }
}
```

I am trying to alter the Title as its currently saying 'Add' for both new and updated content. I've tried routeConfig as well (which threw an error), just wondering if I am close, to finding the right code? Do I need to do some sort of push this.router.push?

**Comment by ClareBear85** [comment]
Whoops this is not in the right place, sorry

**Comment by danielpquinn** [comment]
No problem :)
